name: superfcm_flutter
description: SuperFCM is the missing frontend to Firebase Cloud Messaging. This package wraps the Firebase Messaging SDK and allows you to integrate with the SuperFCM platform.
version: 0.1.2
homepage: https://superfcm.com
repository: https://github.com/superfcm/superfcm-flutter-sdk
topics:
  - fcm
  - push-notifications
  - firebase
  - superfcm

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^12.1.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter:
    sdk: flutter
  flutter_timezone: ^5.0.0
  http: ^1.2.2
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.20.2
  ipapi: ^2.0.0
  json_annotation: ^4.9.0
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.2.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
